# Generated by Django 5.0.6 on 2024-06-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='body',
        ),
    ]
